version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm ci
      - run:
          name: test
          command: npm test
